# Cross-linking map for service pages.
# For each sub-service: its category label, the parent hub it belongs under,
# and the 3-4 genuinely related services a client on this page will also need.
# Titles are looked up from TITLES so links render with proper names.

TITLES = {
    # hubs
    'planning-applications': 'Planning Applications',
    'feasibility-studies': 'Feasibility Studies',
    'site-analysis': 'Site Analysis',
    'bim': 'Building Information Modelling',
    'masterplanning-urban-design': 'Masterplanning & Urban Design',
    'listed-buildings': 'Listed Buildings',
    'conservation-areas': 'Conservation Areas',
    'principal-designer': 'Principal Designer',
    # subs
    'rear-extension': 'Rear Extension',
    'side-extension': 'Side Extension',
    'wrap-around-extension': 'Wrap-around Extension',
    'loft-conversion': 'Loft Conversion',
    'basement-conversion': 'Basement Conversion',
    'garage-conversion': 'Garage Conversion',
    'hmo-conversion': 'HMO Conversion',
    'barn-conversion': 'Barn Conversion',
    'smart-flat-conversion': 'Flat Conversion',
    'kitchen-renovation': 'Kitchen Renovation',
    'bathroom-renovation': 'Bathroom Renovation',
    'bedroom-renovation': 'Bedroom Renovation',
    'chimney-removal': 'Chimney Removal',
    'wall-removal': 'Wall Removal',
    'structural-calculations': 'Structural Calculations',
    'crack-inspection': 'Crack Inspection',
    'structural-inspection': 'Structural Inspection',
    'snagging-survey': 'Snagging Survey',
    'property-condition-survey': 'Property Condition Survey',
    'structural-report': 'Structural Report',
    'party-wall-award': 'Party Wall Awards',
    'boundary-dispute-solutions': 'Boundary Disputes',
    'build-over-agreements': 'Build Over Agreements',
    'outbuild-design': 'Outbuilding Design',
    'sunroom': 'Sunroom',
    'dropped-kerb': 'Dropped Kerb',
    'new-homes': 'New Homes',
    'conservatory': 'Conservatory',
}

# category label shown in the breadcrumb, and the hub each sub sits closest to
CATEGORY = {
    'rear-extension': 'Home Extension',
    'side-extension': 'Home Extension',
    'wrap-around-extension': 'Home Extension',
    'loft-conversion': 'Home Conversion',
    'basement-conversion': 'Home Conversion',
    'garage-conversion': 'Home Conversion',
    'hmo-conversion': 'Home Conversion',
    'barn-conversion': 'Home Conversion',
    'smart-flat-conversion': 'Home Conversion',
    'kitchen-renovation': 'Renovation & Remodelling',
    'bathroom-renovation': 'Renovation & Remodelling',
    'bedroom-renovation': 'Renovation & Remodelling',
    'chimney-removal': 'Renovation & Remodelling',
    'wall-removal': 'Structural Engineering',
    'structural-calculations': 'Structural Engineering',
    'crack-inspection': 'Survey & Inspection',
    'structural-inspection': 'Survey & Inspection',
    'snagging-survey': 'Survey & Inspection',
    'property-condition-survey': 'Survey & Inspection',
    'structural-report': 'Survey & Inspection',
    'party-wall-award': 'Heritage & Compliance',
    'boundary-dispute-solutions': 'Heritage & Compliance',
    'build-over-agreements': 'Heritage & Compliance',
    'outbuild-design': 'Architectural Design & Planning',
    'sunroom': 'Home Extension',
    'dropped-kerb': 'Architectural Design & Planning',
    'new-homes': 'Architectural Design & Planning',
    'conservatory': 'Home Extension',
}

# the parent hub page each sub routes up to
PARENT = {
    'rear-extension': 'planning-applications',
    'side-extension': 'planning-applications',
    'wrap-around-extension': 'planning-applications',
    'loft-conversion': 'planning-applications',
    'basement-conversion': 'planning-applications',
    'garage-conversion': 'planning-applications',
    'hmo-conversion': 'planning-applications',
    'barn-conversion': 'planning-applications',
    'smart-flat-conversion': 'planning-applications',
    'kitchen-renovation': 'feasibility-studies',
    'bathroom-renovation': 'feasibility-studies',
    'bedroom-renovation': 'feasibility-studies',
    'chimney-removal': 'principal-designer',
    'wall-removal': 'principal-designer',
    'structural-calculations': 'bim',
    'crack-inspection': 'site-analysis',
    'structural-inspection': 'site-analysis',
    'snagging-survey': 'principal-designer',
    'property-condition-survey': 'site-analysis',
    'structural-report': 'site-analysis',
    'party-wall-award': 'principal-designer',
    'boundary-dispute-solutions': 'site-analysis',
    'build-over-agreements': 'site-analysis',
    'outbuild-design': 'planning-applications',
    'sunroom': 'planning-applications',
    'dropped-kerb': 'planning-applications',
    'new-homes': 'feasibility-studies',
    'conservatory': 'planning-applications',
}

# genuinely related services — what a client on this page will also need
RELATED = {
    'rear-extension': ['wrap-around-extension', 'wall-removal', 'structural-calculations', 'party-wall-award'],
    'side-extension': ['wrap-around-extension', 'rear-extension', 'party-wall-award', 'wall-removal'],
    'wrap-around-extension': ['rear-extension', 'side-extension', 'wall-removal', 'structural-calculations'],
    'loft-conversion': ['structural-calculations', 'party-wall-award', 'rear-extension', 'snagging-survey'],
    'basement-conversion': ['structural-calculations', 'party-wall-award', 'build-over-agreements', 'structural-report'],
    'garage-conversion': ['loft-conversion', 'structural-calculations', 'kitchen-renovation', 'wall-removal'],
    'hmo-conversion': ['loft-conversion', 'property-condition-survey', 'structural-calculations', 'bathroom-renovation'],
    'barn-conversion': ['structural-report', 'structural-calculations', 'property-condition-survey', 'new-homes'],
    'smart-flat-conversion': ['property-condition-survey', 'structural-calculations', 'kitchen-renovation', 'bathroom-renovation'],
    'kitchen-renovation': ['wall-removal', 'rear-extension', 'bathroom-renovation', 'structural-calculations'],
    'bathroom-renovation': ['kitchen-renovation', 'bedroom-renovation', 'loft-conversion', 'snagging-survey'],
    'bedroom-renovation': ['loft-conversion', 'bathroom-renovation', 'kitchen-renovation', 'chimney-removal'],
    'chimney-removal': ['structural-calculations', 'wall-removal', 'structural-report', 'party-wall-award'],
    'wall-removal': ['structural-calculations', 'rear-extension', 'kitchen-renovation', 'structural-report'],
    'structural-calculations': ['wall-removal', 'structural-report', 'rear-extension', 'loft-conversion'],
    'crack-inspection': ['structural-report', 'structural-inspection', 'property-condition-survey', 'structural-calculations'],
    'structural-inspection': ['structural-report', 'crack-inspection', 'property-condition-survey', 'structural-calculations'],
    'snagging-survey': ['property-condition-survey', 'structural-inspection', 'new-homes', 'structural-report'],
    'property-condition-survey': ['structural-report', 'structural-inspection', 'crack-inspection', 'snagging-survey'],
    'structural-report': ['structural-calculations', 'structural-inspection', 'crack-inspection', 'property-condition-survey'],
    'party-wall-award': ['boundary-dispute-solutions', 'build-over-agreements', 'basement-conversion', 'rear-extension'],
    'boundary-dispute-solutions': ['party-wall-award', 'build-over-agreements', 'property-condition-survey', 'dropped-kerb'],
    'build-over-agreements': ['basement-conversion', 'party-wall-award', 'structural-report', 'boundary-dispute-solutions'],
    'outbuild-design': ['sunroom', 'garage-conversion', 'new-homes', 'dropped-kerb'],
    'sunroom': ['conservatory', 'rear-extension', 'outbuild-design', 'kitchen-renovation'],
    'dropped-kerb': ['outbuild-design', 'boundary-dispute-solutions', 'new-homes', 'garage-conversion'],
    'new-homes': ['structural-calculations', 'property-condition-survey', 'outbuild-design', 'barn-conversion'],
    'conservatory': ['sunroom', 'rear-extension', 'outbuild-design', 'kitchen-renovation'],
}
